# Generated by Django 4.0.3 on 2022-03-09 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
