# Generated by Django 4.0.3 on 2022-03-09 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('qno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('question', models.TextField(blank=True, null=True)),
                ('option_a', models.TextField(null=True)),
                ('option_b', models.TextField(null=True)),
                ('option_c', models.TextField(null=True)),
                ('option_d', models.TextField(null=True)),
                ('marks', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('quizId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz_admin.addquiz')),
            ],
        ),
    ]
