# Generated by Django 4.0.3 on 2022-03-09 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0003_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='qno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
