# Generated by Django 4.0.1 on 2022-03-10 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0006_question_id_alter_question_qno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(max_length=300, null=True)),
                ('date', models.DateField()),
            ],
        ),
    ]
