# Generated by Django 4.0.1 on 2022-03-10 08:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0007_addcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcategory',
            name='date',
        ),
        migrations.AddField(
            model_name='addcategory',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
