# Generated by Django 4.0.1 on 2022-03-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0008_remove_addcategory_date_addcategory_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qno', models.CharField(max_length=3, null=True)),
                ('question', models.TextField(null=True)),
                ('option_a', models.TextField(null=True)),
                ('option_b', models.TextField(null=True)),
                ('option_c', models.TextField(null=True)),
                ('option_d', models.TextField(null=True)),
                ('subject_name', models.CharField(max_length=300, null=True)),
                ('marks', models.IntegerField(null=True)),
                ('answer', models.CharField(max_length=1, null=True)),
                ('quizId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quiz_admin.addquiz')),
            ],
        ),
    ]
