# Generated by Django 4.0.1 on 2022-03-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_admin', '0009_questiondemo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiondemo',
            name='quizId',
        ),
    ]
