# Generated by Django 4.0.1 on 2022-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('quizId', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=300, null=True)),
                ('user_name', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('quiz_time', models.IntegerField(null=True)),
                ('score', models.CharField(max_length=300, null=True)),
                ('maxscore', models.CharField(max_length=300, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCard',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('quizId', models.CharField(max_length=200)),
                ('subject_name', models.CharField(max_length=300, null=True)),
                ('score', models.CharField(max_length=300, null=True)),
                ('maxscore', models.CharField(max_length=300, null=True)),
                ('result', models.CharField(max_length=300, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
